### ISSUE TITLE
How to delete the theme installed in the theme list?

### ISSUE THREAD

**Issue by lamysafari** [golf1052/base16-generator#11]
How can i delete them? thx

**Comment by golf1052** [comment]
Do you mean remove a theme from appearing in the "Base 16: Activate Theme" list or do you mean the "Preferences: Color Theme" list?

**Comment by lamysafari** [comment]
In the "Preferences: Color Theme" list

**Comment by golf1052** [comment]
I have published version 1.9.0 which introduces a new command, `Base16: Deactivate Theme` which will deactivate the currently activated Base16 theme. Please re-open this issue if you have any issues.
