### ISSUE TITLE
Add a "Activate All" command

### ISSUE THREAD

**Issue by golf1052** [golf1052/base16-generator#16]

**Comment by stedingan** [comment]
This would be a very helpful feature!
I am also questioning why you don't use this as the default and activate all themes by default?

**Comment by golf1052** [comment]
There are 200+ themes available and most people typically use 1 theme at a time so I didn't want to over clutter the theme list. The intention of the "Activate All" command would be to let users quickly browse through themes to see which one they like.

**Comment by stedingan** [comment]
On the other hand if you want to switch to a new theme or as you said browse through themes you have a lot of work ahead of you.

You need to activate the theme and then do two reloads.

**Comment by golf1052** [comment]
Agree, it's currently a pain to try and check out new themes so I want to add this new option for users. I don't think it makes sense to have it as the default however.

**Comment by stedingan** [comment]
That's awesome to hear.

Keep up the awesome work. It's the best base16 plugin for vscode by far! :-)

**Comment by golf1052** [comment]
This is now supported as of version 1.13.0, see 941b13d98bcceeff7d65026767de93babcded214
