### ISSUE TITLE
Markdown preview text is wrong

### ISSUE THREAD

**Issue by martinlindhe** [golf1052/base16-generator#2]
Hello & thanks for a great tool!

Using the "Base16 Twilight Dark" theme, and running from the Command Palette "Markdown: Open preview on the side", I get the following appearance:

![preview-base16-twilight-dark](https://user-images.githubusercontent.com/181531/30109294-21e3c7c4-9306-11e7-9bf2-898b18be05e1.png)

Switching back to built in theme "Dark (Visual Studio)", it looks like this:

![preview-good](https://user-images.githubusercontent.com/181531/30109303-28b8dd64-9306-11e7-809b-a5d2fad227e7.png)

**Comment by golf1052** [comment]
Looks like this theme was mistakenly marked as a "light" UI theme instead of as a "dark" UI theme. I've pushed 1.1.1 which fixes this.

Thanks for the bug report!

**Comment by martinlindhe** [comment]
Fantastic, thank you so much for the quick fix!
