### ISSUE TITLE
Publish to Open VSX

### ISSUE THREAD

**Issue by SimonBrazell** [golf1052/base16-generator#24]
Instructions found [here](https://github.com/eclipse/openvsx/wiki/Publishing-Extensions), this would allow those using [VSCodium](https://github.com/VSCodium/vscodium) and other VS Code compatible editors to use these themes too.

**Comment by golf1052** [comment]
Now published on Open VSX https://open-vsx.org/extension/golf1052/base16-generator

I've created an [issue](https://github.com/eclipse/open-vsx.org/issues/128) on the open-vsx repo to claim ownership of the namespace. Once that's been confirmed I'll publish a new version of the extension (at some point) to remove the warning.

Thanks for the suggestion!

**Comment by SimonBrazell** [comment]
Just tried it out, works great, thanks heaps!
