### ISSUE TITLE
Tomorrow Dark and Tomorrow Light are flipped! 😬

### ISSUE THREAD

**Issue by chriskrycho** [golf1052/base16-generator#3]
If you activate **Tomorrow Dark** you get **Tomorrow Light** and vice versa.

**Comment by golf1052** [comment]
I've redone the generate themes logic. Tomorrow Dark and Light are now correct. 3 other themes were also fixed. I've pushed 1.2.0 which fixes this. Thanks for the report!

**Comment by chriskrycho** [comment]
Awesome, and thank you! 👏
