### ISSUE TITLE
Tomorrow Night?

### ISSUE THREAD

**Issue by darrinholst** [golf1052/base16-generator#31]
What happened to the tomorrow night themes? Is there any alternative for those of us that were using them?

**Comment by darrinholst** [comment]
right click, Install Another Version...

Would still be nice not to have themes removed out from under us

**Comment by melck** [comment]
I'm a big fan of Tomorrow night themes too. This extensions is installed only for that themes.

**Comment by golf1052** [comment]
The original author deleted the repo containing the Tomorrow themes. I'll be able to re-add them with https://github.com/base16-project/base16-schemes but there will need to be some code changes considering this will be a new source.

**Comment by darrinholst** [comment]
oh man, I didn't realize there was so much 🍿 going on around base16. Can't we have nice things? 😏

**Comment by golf1052** [comment]
[1.17.0](https://marketplace.visualstudio.com/items?itemName=golf1052.base16-generator) is now available with the Tomorrow themes re-added (Tomorrow, Tomorrow Night, and Tomorrow Night Eighties)

**Comment by darrinholst** [comment]
Appreciate the quick turnaround on this. 👍
