### ISSUE TITLE
Moving to tinted-theming?

### ISSUE THREAD

**Issue by JamyGolden** [golf1052/base16-generator#36]
Hey @golf1052 we have light/dark `variants` in the schemes repo now for every scheme, which helps not needing to manipulate the generated code with scripts: https://github.com/tinted-theming/schemes/blob/spec-0.11/base16/da-one-ocean.yaml#L4

Are you still interesting in moving this repo to Tinted Theming and being a maintainer on the project?

**Comment by alexwforsythe** [comment]
Check out this extension (from #30): https://github.com/tinted-theming/tinted-vscode

**Comment by JamyGolden** [comment]
I'm going to close this, we ended up creating [tinted-vscode](https://marketplace.visualstudio.com/items?itemName=TintedTheming.base16-tinted-themes) which is a vscode extension for base16 and base24.
